# ==========================
# Variable definitions
# ==========================
variables:
  NUM_GPUS: 8
  MINI_BATCH_SIZE: 16
  PER_GPU_BATCH_SIZE: 1
  TENSOR_MODEL_PARALLEL_SIZE: 2
  NUM_ROLLOUTS: 8
  BASE_MODEL: Qwen/Qwen2.5-7B-Instruct
  PROJECT_NAME: EMPO2-ScienceWorld
  TASK_NUM: ${oc.env:TASK_NUM,25}
  TRIAL: ${oc.env:TRIAL,0}
  EXPERIMENT_NAME: grpo-${variables.TASK_NUM}-sciworld-${variables.TRIAL}
  DATA_DIR: agl_envs/task_data/scienceworld/single_data/${variables.TASK_NUM}
  OUTPUT_DIR: empo2_grpo_checkpoint/${variables.EXPERIMENT_NAME}

# ==========================
# Main Config
# ==========================
agentlightning:
  port: 9999

algorithm:
  adv_estimator: grpo
  use_kl_in_reward: false
  use_final_reward_as_step_reward: false
  use_intrinsic_reward: true

data:
  train_files: ${variables.DATA_DIR}/train.parquet
  val_files: ${variables.DATA_DIR}/test.parquet
  train_batch_size: 16
  val_batch_size: 80
  max_prompt_length: 4500
  max_response_length: 32
  max_train_length: 4500
  truncation: error
  return_raw_chat: true

actor_rollout_ref:
  rollout:
    tensor_model_parallel_size: ${variables.TENSOR_MODEL_PARALLEL_SIZE}
    n: ${variables.NUM_ROLLOUTS}
    log_prob_micro_batch_size_per_gpu: ${variables.PER_GPU_BATCH_SIZE}
    multi_turn:
      format: hermes
    name: vllm
    gpu_memory_utilization: 0.5
    enable_chunked_prefill: false
    enforce_eager: false
    free_cache_engine: true
    val_kwargs:
      temperature: 0.4
      do_sample: true
  actor:
    ppo_mini_batch_size: ${variables.MINI_BATCH_SIZE}
    ppo_micro_batch_size_per_gpu: ${variables.PER_GPU_BATCH_SIZE}
    optim:
      lr: 1.0e-6
    use_kl_loss: false
    kl_loss_coef: 0.00
    entropy_coeff: 0.0
    clip_ratio_high: 0.30
    clip_ratio_low: 0.20
    clip_ratio_c: 10.0
    fsdp_config:
      param_offload: true
      optimizer_offload: true
  ref:
    log_prob_micro_batch_size_per_gpu: ${variables.PER_GPU_BATCH_SIZE}
    fsdp_config:
      param_offload: true
  model:
    path: ${variables.BASE_MODEL}
    use_remove_padding: true
    enable_gradient_checkpointing: true

trainer:
  default_local_dir: ${variables.OUTPUT_DIR}/checkpoints
  n_gpus_per_node: ${variables.NUM_GPUS}
  val_before_train: false
  critic_warmup: 0
  logger:
    - console
    - wandb
  project_name: ${variables.PROJECT_NAME}
  experiment_name: ${variables.EXPERIMENT_NAME}
  nnodes: 1
  save_freq: 50
  test_freq: 20
  total_epochs: 500
