[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "epc_awkit"
version = "0.3.6"
authors = [
  { name="Zhuofeng Li", email="zhuofengli@tamu.edu" },
  { name="Haoxiang Zhang", email="haz140@ucsd.edu" },
  { name="Pan Lu", email="lupantech@gmail.com" },
]
description = "EPC_AW is a training-free agentic framework for mitigating the epsitemic miscalibration in the planning phase of LLM-MAS."
readme = "README.md"
requires-python = ">=3.10"
dynamic = ["dependencies"]

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[tool.setuptools.packages.find]
where = ["."]
include = ["epc_aw"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}


[project.optional-dependencies]
dev = [
    "black>=25.1.0",
    "isort>=6.0.1"
]

[tool.black]
line-length = 88
target-version = ['py310']

[tool.isort]
profile = "black"